/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 truckLowPoly.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/truckLowPoly.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} scale={1.188}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.dark} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.dark2} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.dark3} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.green2} />
      </group>
    </group>
  );
}

useGLTF.preload("/truckLowPoly.glb");
